### ISSUE TITLE
La programmation fonctionnelle (en JavaScript) pour les nuls

### ISSUE THREAD

**Issue by alvinberthelot** [hello-world-conference/conference#1]
La **programmation fonctionnelle** vous en avez forcément entendu parler, mais ce paradigme de programmation vous paraît bien abstrait. Et puis quelles sont les raisons qui vous pousseraient à la mettre en pratique plutôt que de garder vos habitudes de développement qui ont fait leurs preuves ?

C'est ce que vous découvrirez dans cet atelier, où **progressivement vous découvrirez les concepts sous-jacents** ; l'immuabilité, les fonctions pures, la transparence référentielle et les fonctions d’ordre supérieur ; **en faisant évoluer et en refactorant une petite application existante**.

Le tout en JavaScript qui, s'il n'est pas le langage de prédilection de ce paradigme, est sans conteste celui qui doit le mettre le plus en pratique de par sa popularité.

Logistique :

- Un ordinateur est souhaitable pour chaque participant

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
