### ISSUE TITLE
Mob Programming

### ISSUE THREAD

**Issue by Max-Git** [hello-world-conference/conference#10]
Le Mob Programming, comme le décrit Woody Zuill est "All the brilliant people working on the same thing, at the same time, in the same space, and on the same computer".  
L'idée est donc de tirer le meilleur de l'équipe afin de produire un code dont la qualité sera bien plus élevée que si on l'avait produit seul ou même en Pair Programming.
Le Mob Programming est également un outil merveilleux pour découvrir et apprendre en équipe, cela renforce la communication, limite les goulots d'étranglement et remise définitivement au placard le mythe du/de la développeur.euse héro.ïne.
Cet atelier peut être effectué en ayant comme exercice les propositions #7 et #5

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
