### ISSUE TITLE
Event Storming

### ISSUE THREAD

**Issue by Max-Git** [hello-world-conference/conference#11]
Comment modéliser un processus métier, même complexe, ou encore l’entièreté du panorama applicatif d’une entreprise sans tomber dans le piège d’une analyse sans fin, épuisante et ô combien ennuyante ?

Comment maîtriser la complexité d’un projet avec agilité en démarrant de la manière la plus appropriée, et ainsi obtenir une très bonne vue d’ensemble dès le départ ?

L'Event Storming est une technique d'analyse très accessible qui vise à acquérir une compréhension détaillée de votre domaine métier. Les outils utilisés lors de ces ateliers, sont des post-its, des marqueurs pour tout le monde et de l’espace, beaucoup d’espace !

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
