### ISSUE TITLE
Coding dojo sur la reprise de code et le turn over

### ISSUE THREAD

**Issue by sfauvel** [hello-world-conference/conference#13]
Les coding dojo sont un excellent moyen de progresser dans sa manière de coder.

Malheureusement, ces sessions sont courtes, et ne permettent pas bien d'appréhender les problématiques liés à la durée des projets.

Cet atelier propose de travailler sur ces aspects.

La forme est celle d'un coding dojo classique en pair/mob programming.

La particularité est que le développement se fera tout au long de la journée. Les personnes viendront contribuer un moment avant de laisser leurs places aux suivants qui reprendront et continueront le travail commencer. 

Celle permettra de s'interroger sur ce qu'on laisse aux futurs équipes et de prendre conscience de ce qui est nécessaire pour simplifier la reprise d'une application. 
On pourra prévoir un temps en fin de journée pour débriefer.

L'atelier durera toute la journée mais les participants pourront venir et repartir comme ils le souhaitent. 
Un rétro projecteur serait un plus ou au moins un grand écran (cela dépend du nombre de personnes). On peut avoir autant de spectateur que l'on veut mais il est préférable de ne pas avoir plus que 6 développeurs en même temps. 

type; workshop
level: intermediate
refinement: already done

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
