### ISSUE TITLE
Refactoring en mode petits pas

### ISSUE THREAD

**Issue by sfauvel** [hello-world-conference/conference#14]
Le refactoring est une bonne chose pour améliorer la qualité de notre code. 
Il y a plusieurs approchent pour modifier du code et certaines sont plus sécurisées que d'autres.
Pour éviter de tomber dans un état instable dont il peut être long avant d'en sortir, il est préférable de procéder par petits pas. L'objectif et de faire évoluer le code en le gardant continuellement fonctionnel. 

On cherchera dans cet atelier à refactorer une application en gardant continuellement les tests au vert. On pourra avoir comme contrainte de lancer les tests à intervalle fréquent (moins de 3mn) et s'ils échouent, on annule les dernières modifications (approche TCR)

type: workshop
level: intermediate
refinement experience

**Comment by bannier** [comment]
Quel serait le langage ?

**Comment by sfauvel** [comment]
A priori Java mais cela pourrait être sur un autre langage s'il y a de la demande, du code intéressant à refactorer et une machine avec un environnement.

**Comment by alvinberthelot** [comment]
Salut @bannier , on va faire inverser la question, quel serait le langage que tu aimerais avoir ? JavaScript ?
Après 2 options sont possibles, soit je reprends le workshop de @sfauvel pour en décliner une version en JavaScript (si c'est possible), soit on se met en binôme et je t'aide pour la traduction Java - JavaScript, la marche n'est pas si haute je pense ; et puis le polyglottisme c'est bien aussi ;)

**Comment by sfauvel** [comment]
Pas de souci pour moi. Je suis ouvert à tout langage. Il faudra par contre la présence de quelqu'un qui connait bien pour l'environnement pour trouver un chemin sûr dans le refactoring (même si beaucoup de principes sont assez indépendants du langage).
Je pense que l'on doit pouvoir du code à refactorer dans tous les langages. Cela ne devrait pas être un problème.
Si vous êtes intéressé par l'atelier, merci d'indiquer le ou les langages avec lesquels vous souhaiteriez le faire.

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
