### ISSUE TITLE
Living documentation

### ISSUE THREAD

**Issue by sfauvel** [hello-world-conference/conference#15]
L'idée de "living documentation" (https://leanpub.com/livingdocumentation) est que notre code soit aussi notre source de documentation.
Mais quelle information peut on réellement extraire du code ? Comment peut on récupérer cette information pour la structure dans une vraie documentation plus utile qu'un Javadoc. 

A partir d'une application existante (ou la votre), nous déterminerons ce dont nous avons besoin pour la prise en main et la compréhension du logiciel. Nous chercherons à extraire ces information depuis le code afin de générer une ou plusieurs documentations couvrant nos besoins. 

type: workshop
level: intermediate
refinement: experience

L'atelier sera en Java

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
