### ISSUE TITLE
Découverte de Rust

### ISSUE THREAD

**Issue by emeric-martineau** [hello-world-conference/conference#17]
Rust le langage de Mozilla a introduit un nouveau concept pour la gestion de la mémoire.
Rust délaisse le garbage collector au profit du borrow checker, du lifetime, du memory ownership...

Nous allons découvrir Rust et parcourir ce que propose ce langage, je vous propose de comparer le fonctionnement d'un garbage collector et de la gestion de mémoire par Rust.
Cette présentation sera le plus objectif possible.
Nous verrons les avantages et inconvénients des deux systèmes.

Nous verrons aussi quelques aspects du langage (programmation fonctionnelle, structure, interface...)

Level: beginner
Type: tiny workshop
Refinement: experience

**Comment by cbossard** [comment]
Merci Émeric pour cette proposition.
Néanmoins, le principe d'Hello World est de ne proposer que des ateliers, et pas de présentation en mode conférence.
As tu la possibilité de proposer ton sujet en atelier ?

-------- Message d'origine --------

**Comment by emeric-martineau** [comment]
Je comptais proposer ça aussi, mais j'ai été interrompu avant de poster l'autre issue :)
Du coup, j'ai modifié.

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
