### ISSUE TITLE
Atelier diagrammes d'architecture C4

### ISSUE THREAD

**Issue by Max-Git** [hello-world-conference/conference#19]
Il n'est pas rare, lorsqu'on demande à une personne de dessiner un diagramme d'architecture, de se retrouver face à un entremêlement de flèches et de patatoïdes difficilement compréhensibles. 
Souvent au sein même d'une équipe, les personnes ont toutes une façon différente de représenter une architecture.
Un autre problème étant le niveau d'information représentée sur un même diagramme.
Tout cela est bien dommage alors qu'un des buts visés par les diagrammes d'architecture est d'identifier les éléments significatifs de structure et d'en avoir une vision partagée par toute l’équipe.
D'aucuns diront qu'il existe l'UML pour ça ! Mais pour moi l'UML c'est comme l’Espéranto, la belle promesse d'un langage unique mais que personne ne parle !
Pour Simon Brown, l'inventeur du modèle C4, un ensemble d’abstractions communes est bien plus utile et efficace qu’une notation commune comme l'UML.
Dans cet atelier, je vous ferai découvrir par la pratique, l'élaboration de diagrammes d'architecture suivant le modèle C4.

**Comment by cbossard** [comment]
Maxime, peux-tu nous donner quelques détails sur 
- le niveau (débutant / intermédiaire / avancé)
- le format (1h30 / 3h)
- si la session est déjà rôdée ou si ce serait la première fois

Merci !

**Comment by Max-Git** [comment]
Débutant / 1h30 / et déjà rodée !
Merci !
