### ISSUE TITLE
Coding dojo pour le web

### ISSUE THREAD

**Issue by alvinberthelot** [hello-world-conference/conference#2]
Du contenu et une mise en forme (illustrée dans un bon vieux power point), le tout devant être codé pour être affiché dans un navigateur. Ça à l’air simple comme ça et il n’y a pas trop de questions à se poser.

Justement si pour une fois on prenait le temps de se poser des questions (à plusieurs) sur la maintenabilité, la compatibilité, la testabilité (et toute autre joyeuseté) de notre code ...

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0

**Comment by alvinberthelot** [comment]
Je suis toujours motivé pour faire cette session pour Hello world 2.0 😉
