### ISSUE TITLE
Lancement d'un projet libre, un rex ho

### ISSUE THREAD

**Issue by gcharbonnier** [hello-world-conference/conference#28]
Un petit mot sur le contexte : à la suite du confinement, je me suis retrouvé sans activité (je suis développeur indépendant avec un peu de remote mais le plus souvent j'interviens chez les clients et la totalité de mes projets engagés ont été repoussés et certains annulés) et un peu désœuvré. Du coup, j'ai décidé de consacrer mon temps au lancement d'un projet libre de système de présentation (à la powerpoint, prezi ou autres slides.io ...). Je me suis pris de passion (faut dire, y a pas grand chose d'autre à faire...) et cela a eu pour conséquence ~~une dégradation drastique de mon sommeil~~ de monter en compétence sur un paquet de sujets ! 

Je propose donc un "retour d'expérience à chaud" sans avoir vraiment les idées très claires sur la forme ni le fond. D'autant que le 7 mai n'est pas pour tout de suite...Plus qu'une présentation, j'aimerai plutôt un échange interactif avec des questions-réponses-commentaires ou chacun pourrait rebondir et partager sa propre expérience...

En vrac des sujets abordables selon l'intérêt ou non des participants...c'est plus une liste désordonnée de thématiques sur lesquelles j'ai du passer un peu de temps - mais pour la plupart d'entre-elles, je ne suis pas expert (et loin sans faut!) : 
* créer un mvp et essayer de s'y tenir...par exemple en identifiant dès le début des milestones simples dans des swimlanes d'un kanboard 👍 
* choisir une licence (dans mon cas c'était la GPL) 🆓 
* déposer une marque auprès de l'INPI (beurk! ai-je bien fait?) 
* préparer la communication, achat de nom de domaine, hébergement, montage d'un cms, traduction, formulaire de contact, génération de site statique...(j'en garde de très mauvais souvenir car je ne fait pas web et je me suis bien pris les pieds dans le tapis avec Wordpress...)
* mise en route de doxygen pour documenter le code dès le début
* mise en place de tests unitaires dès le début...zut j'ai zappé ça (c'est mal...mea maxima culpa 😳 ..et pourtant j'en ai pas vraiment ressenti le besoin ) 
* mattermost pour échanger avec la communauté
* mise en route de l'intégration continue avec Github actions - build (& release éventuelle) sur Linux, MacOs, Windows...c'est génial ce truc, comment on faisait avant ?
* teasing...mince c'est quoi
* réfléchir sur le business model...euh ça aurait pas été mieux de le faire au début, non ? 🤔 
* ... 
Bref, un sujet assez large, pas forcément technique...et à (re)définir en fonction de vos retours !

Pour celles et ceux que le projet pourrait intéresser, son nom est Swag (un logiciel de présentation libre - https://swagsoftware.net - https://github.com/a-team-fr/swag).

Pour les labels : je verrai bien level:beginner, refinement:experience et type:forum
Remarque importante : si on est encore confiné le 7 mai (probable...), je serai extrêmement limité par la qualité exécrable de ma connexion (j'habite à proximité de la réserve naturelle du lac de gdlieu...du coup, pas de relais mobile et un dslam à perpet). Discord ça passe à peu près mais dès que partage un écran c'est mort, Jitsi / 8x8 lag rapidement, Hangout ç'est presque potable mais c'est google...whatsapp (ça va pas la tête ? et pourquoi pas zoom tant qu'on y est ?!!! ) - bref, ça serait bien un outil miracle vraiment light et si possible libre...

**Comment by alvinberthelot** [comment]
Salut Guillaume,

Hello World repose sur le fait que tout le monde doit participer, que ce soit en atelier (workshop) ou dans un groupe de discussion (forum), donc je te rassure tout de suite on est loin du principe de présentation où un conférencier parle et les autres écoutent, en remote en plus je ne t'explique même pas 😴

Si c'est un forum, tu n'es pas non plus obligé d'être expert sur le sujet puisque tous les participants vont apporter quelque chose à la discussion, tu dois avoir un peu de matière pour lancer le sujet si c'est toi qui propose, mais c'est tout.

Par contre, il te faut :

1. Un sujet clair sur la discussion, de quoi allez vous discuter ? Qu'est ce que vous allez apprendre ensemble ?

2. Un sujet inclusif, sinon les échanges ne se feront que dans un seul sens et naturellement cela repartira sur un retour d'expérience de ta part plus qu'un forum.

3. Un sujet ciblé sur les connaissances des participants, est que c'est un Hello World ;) pour les débutants ou un sujet hardcore pour les initiés ?

Par rapport à l'ensemble des sujets que tu as énoncé je te conseille de ne pas trop proposer de sujets relatifs au business, communication, marketing car ce n'est pas vraiment la cible des participants en général. A la limite tu peux en proposer un, pour le coup avec une thématique assez large, du style : 

- type : forum ; level : intermediate ; "Moi développeur, j'ai voulu lancer un produit"

Sinon il y a d'autres sujets qui me viennent en tête :

-  type : forum ; level : intermediate ;  "Quelles sont les bonnes pratiques pour documenter son code ?"

- type : tiny workshop ; level : beginner ; "Initiation à l'intégration continue avec GitHub"

- type : workshop ; level : beginner ; "Découvrir le C++ avec les tests unitaires"

Voilà il s'agit de 4 idées de proposition par rapport à ce que tu as évoqué, ce n'est en rien obligatoire de proposer cela et sous ces formats là. C'est juste pour te guider un peu mieux pour rédiger tes propositions. Car tu verras que des sujets proposés il y en aura beaucoup plus que les issues actuellement le jour J et ce n'est pas toujours facile de faire émerger un programme à chaud. Il te faudra décrire tes propositions (forcément en un temps limité) à des personnes que tu ne connais pas, pour susciter leur intérêt.

C'est pour ça aussi qu'on voulait mettre des labels sur les propositions : [https://github.com/hello-world-conference/conference/labels](https://github.com/hello-world-conference/conference/labels)

En préparant tes propositions à l'avance en te posant certaines questions, tu auras les idées claires sur ce que tu veux apporter aux autres et ça sera bénéfique pour tout le monde 😀

Du coup je vais fermer cette issue (tu pourras toujours interagir dessus avec nous si tu le souhaites) et je te laisse **en créer une pour chaque proposition que tu veux faire**, je suis persuadé qu'elles vont être top 🤘😉
