### ISSUE TITLE
Faire une première contribution open source

### ISSUE THREAD

**Issue by cbossard** [hello-world-conference/conference#3]
Pas toujours facile de se lancer pour faire une première contribution à un projet open source.
Utilisation de GitHub / GitLab / ..., pull request, merge, ... tout ça peut parfois paraître un peu obscur.
Et si nous le faisions ensemble ?
On trouve un projet qui nous plaît, un bug taggé "good first issue", et c'est parti !

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0

**Comment by cbossard** [comment]
Motivée pour recommencer en v2 !
