### ISSUE TITLE
DDD et TDD sont dans un bateau...

### ISSUE THREAD

**Issue by abailly** [hello-world-conference/conference#5]
Le _Domain-Driven Design_ est l'art de concevoir des logiciels qui soient congrus au domaine fonctionnel qu'ils sont supposés représenter, en mettant au centre du processus de développement les interactions avec les experts du domaine et leur _langage_, en s'abstrayant au maximum de la "colle" et du "socle technique". 
Le _Type-Driven Development_ est l'art d'utiliser les _types_ pour guider l'écriture du code, une sorte de _Test-Driven Development_ dans lequel les tests seraient exécutés par le compilateur. 
Cette session propose d'explorer la conjonction de ces deux approches sous la forme d'un atelier de code qui sera aussi une initiation aux types algébriques et dépendants. 

type: workshop
level: intermediate/advanced

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
