### ISSUE TITLE
[meta] Impossible d'ajouter des labels si on n'est pas committer

### ISSUE THREAD

**Issue by abailly** [hello-world-conference/conference#6]

**Comment by alvinberthelot** [comment]
Salut @abailly

Oui en effet cela n'est pas possible et malheureusement GiHub n'a pas de configuration qui pourrait changer cette permission.

Pour l'instant je ne peux que te proposer de rajouter à la fin de ton résumé d'atelier les labels en mode textuel et nous on repassera derrière pour les rajouter 😞

Je vais changer le README en conséquence.
