### ISSUE TITLE
Au-delà du test unitaire

### ISSUE THREAD

**Issue by abailly** [hello-world-conference/conference#7]
Tout le monde (ahem!) utilise des tests unitaires pour écrire son code, si possible avant d'écrire le code de production. Mais ces tests sont souvent verbeux, parfois lourd à maintenir, et leur multiplication peut rendre difficile la compréhension générale de l'intention, des _propriétés_ qu'un code est supposé respecter.
Cette session propose une introduction par la pratique au _test de propriétés_ et plus généralement au _test à base de modèles_, une technique et un ensemble d'outils permettant de tester plus et mieux, d'exprimer de manière plus concise les intentions et les propriétés attendues de notre code. 
On utilisera le langage python et le framework[hypothesis](https://hypothesis.readthedocs.io/en/latest/).

level: intermédiaire
type: workshop

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
