### ISSUE TITLE
Green IT : quelles actions peut-on mettre en place en tant que dev ?

### ISSUE THREAD

**Issue by cbossard** [hello-world-conference/conference#8]
Quelles actions concrètes mettre en oeuvre de manière simple pour essayer de limiter l'impact écologique de nos développements ?
Quelles marges de manoeuvre avons-nous en tant que devs ? 
Faut-il obligatoirement une volonté de la direction pour s'orienter vers une démarche plus verte ?

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
