### ISSUE TITLE
On mange où ?

### ISSUE THREAD

**Issue by aucoin** [hello-world-conference/conference#9]
Et si nous nous mettions tous autour d'une table pour décider ensemble où aller manger ce midi ? Nous allons être plusieurs, beaucoup auront certainement leurs préférences. 
Dans un contexte où chacun est libre de s'exprimer, les avis divergent, mais une réponse doit pourtant être apportée.
Comment faire pour que les discussions restent constructives et ne s'enveniment pas ? 
Certes, il ne s'agit pas là d'une situation avec beaucoup d'enjeux, mais si nous testions quelques outils pour tenter de communiquer de manière apaisée et répondre le mieux possible à cette question cruciale : on mange où ?

**Comment by hello-world-conference** [comment]
Session proposée lors de Hello world 1.0
